apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: akspoc
  name: akspoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akspoc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: akspoc
    spec:
      containers:
      - image: pbpoc.azurecr.io/akspoc:0.0.1-SNAPSHOT
        name: akspoc
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
status: {}
